"""Updated models

Revision ID: 0e4a9a2ec7e8
Revises: ceebc16e7fc6
Create Date: 2024-12-30 12:38:04.360952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e4a9a2ec7e8'
down_revision: Union[str, None] = 'ceebc16e7fc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
