"""Updated models

Revision ID: 13967ff21ba8
Revises: dd9535beae80
Create Date: 2024-12-03 15:48:44.166167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13967ff21ba8'
down_revision: Union[str, None] = 'dd9535beae80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_credentials', sa.Column('exchange_name', sa.String(length=255), nullable=True))
    op.add_column('user_credentials', sa.Column('oauth2_token', sa.LargeBinary(), nullable=True))
    op.alter_column('user_credentials', 'encrypted_apikey',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.alter_column('user_credentials', 'encrypted_secret_key',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.alter_column('user_credentials', 'encrypted_passphrase',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_credentials', 'encrypted_passphrase',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.alter_column('user_credentials', 'encrypted_secret_key',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.alter_column('user_credentials', 'encrypted_apikey',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.drop_column('user_credentials', 'oauth2_token')
    op.drop_column('user_credentials', 'exchange_name')
    # ### end Alembic commands ###
