"""Added SubscriptionPlan and Bot models

Revision ID: 3c05531db2d1
Revises: 003cf2162e58
Create Date: 2025-01-01 17:00:19.529316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c05531db2d1'
down_revision: Union[str, None] = '003cf2162e58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monthly_subscription')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_subscription',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('subscription_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('subscription_plan_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['subscription_plan_id'], ['subscription_plans.id'], name='monthly_subscription_subscription_plan_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='monthly_subscription_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='monthly_subscription_pkey')
    )
    # ### end Alembic commands ###
