"""Added SubscriptionPlan and Bot models

Revision ID: 540222424dd2
Revises: 7edef6762ea0
Create Date: 2025-01-18 11:37:15.390990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '540222424dd2'
down_revision: Union[str, None] = '7edef6762ea0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logic_parameters', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('bots', sa.Column('bot_definition_id', sa.UUID(), nullable=False))
    op.alter_column('bots', 'strategy',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_foreign_key(None, 'bots', 'bot_definitions', ['bot_definition_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bots', type_='foreignkey')
    op.alter_column('bots', 'strategy',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('bots', 'bot_definition_id')
    op.drop_table('bot_definitions')
    # ### end Alembic commands ###
