"""Added SubscriptionPlan and Bot models

Revision ID: 7cce1a8f95fb
Revises: 55a8664ebf88
Create Date: 2025-01-01 16:56:04.970822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7cce1a8f95fb'
down_revision: Union[str, None] = '55a8664ebf88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('max_linked_accounts', sa.Integer(), nullable=False),
    sa.Column('max_bots', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('features', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('strategy', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('profit_loss', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run', sa.DateTime(timezone=True), nullable=True),
    sa.Column('configuration', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('extra_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_pnl_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bot_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=False),
    sa.Column('roe', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('accounts', 'account_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('accounts', 'type',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('google_oauth', 'access_token',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('google_oauth', 'refresh_token',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('google_oauth', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.add_column('historical_searched_cryptos', sa.Column('searched_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('historical_searched_cryptos', 'searched_symbol',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('historical_searched_cryptos', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('historical_searched_cryptos', 'searchet_at')
    op.add_column('monthly_subscription', sa.Column('subscription_plan_id', sa.UUID(), nullable=False))
    op.alter_column('monthly_subscription', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('monthly_subscription', 'status',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_foreign_key(None, 'monthly_subscription', 'subscription_plans', ['subscription_plan_id'], ['id'])
    op.alter_column('starred_cryptos', 'symbol',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('starred_cryptos', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('starred_cryptos', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('starred_cryptos', 'symbol',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint(None, 'monthly_subscription', type_='foreignkey')
    op.alter_column('monthly_subscription', 'status',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('monthly_subscription', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('monthly_subscription', 'subscription_plan_id')
    op.add_column('historical_searched_cryptos', sa.Column('searchet_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.alter_column('historical_searched_cryptos', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('historical_searched_cryptos', 'searched_symbol',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('historical_searched_cryptos', 'searched_at')
    op.alter_column('google_oauth', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('google_oauth', 'refresh_token',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('google_oauth', 'access_token',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('accounts', 'type',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('accounts', 'account_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_table('bot_pnl_history')
    op.drop_table('bots')
    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
