"""Added SubscriptionPlan and Bot models

Revision ID: 7edef6762ea0
Revises: 3c05531db2d1
Create Date: 2025-01-14 15:32:32.764600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7edef6762ea0'
down_revision: Union[str, None] = '3c05531db2d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('user_configuration', sa.Column('dark_mode', sa.Boolean(), nullable=True))
    op.add_column('user_configuration', sa.Column('currency', sa.String(length=3), 
                                                  server_default='usd',  # <-- NEW
                                                  nullable=False))
    op.add_column('user_configuration', sa.Column('language', sa.String(length=10),
                                                  server_default='english',  # <-- NEW
                                                  nullable=False))
    op.add_column('user_configuration', sa.Column('notifications', sa.String(length=20),
                                                  server_default='most-recent',  # <-- NEW
                                                  nullable=False))
    op.drop_column('user_configuration', 'bio')



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_configuration', sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('user_configuration', 'notifications')
    op.drop_column('user_configuration', 'language')
    op.drop_column('user_configuration', 'currency')
    op.drop_column('user_configuration', 'dark_mode')
    # ### end Alembic commands ###
