"""Updated models

Revision ID: 9523b1ef1ff4
Revises: 84c6bf6a0358
Create Date: 2024-12-30 12:27:19.364744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9523b1ef1ff4'
down_revision: Union[str, None] = '84c6bf6a0358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
