version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
    - postgres_data:/var/lib/postgresql/data
    networks:
    - my_network
    ports:
    - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis_tasks
    volumes:
    - redis_data:/data
    networks:
    - my_network
    ports:
    - "6379:6379"

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scheduler_v1
    depends_on:
    - postgres
    - redis
    networks:
    - my_network
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres_db:5432/${POSTGRES_DB}
      REDIS_URL: redis://redis_tasks:6379
    ports:
    - "80:80"

volumes:
  postgres_data:
  redis_data:


networks:
  my_network:
    driver: bridge
