"""Updated models

Revision ID: 0243a593d85b
Revises: 6a315141ea4f
Create Date: 2024-10-14 10:01:39.713380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0243a593d85b'
down_revision: Union[str, None] = '6a315141ea4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_configuration', sa.Column('location', sa.Text(), nullable=True))
    op.add_column('user_configuration', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('user_configuration', sa.Column('webpage_url', sa.Text(), nullable=True))
    op.add_column('user_configuration', sa.Column('trading_experience', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_configuration', 'trading_experience')
    op.drop_column('user_configuration', 'webpage_url')
    op.drop_column('user_configuration', 'bio')
    op.drop_column('user_configuration', 'location')
    # ### end Alembic commands ###
