"""Updated models

Revision ID: 0edd3867bad7
Revises: 1bb8a8fbfcde
Create Date: 2024-10-09 11:20:06.909963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0edd3867bad7'
down_revision: Union[str, None] = '1bb8a8fbfcde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Drop the foreign key constraints before altering columns
    op.drop_constraint('historical_pnl_account_id_fkey', 'historical_pnl', type_='foreignkey')
    op.drop_constraint('user_credentials_account_id_fkey', 'user_credentials', type_='foreignkey')
    
    # Alter the columns
    op.alter_column('accounts', 'id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using="id::uuid")

    op.alter_column('historical_pnl', 'account_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using="account_id::uuid")

    op.alter_column('user_credentials', 'account_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using="account_id::uuid")

    # Re-add the foreign key constraints
    op.create_foreign_key('historical_pnl_account_id_fkey', 'historical_pnl', 'accounts', ['account_id'], ['id'])
    op.create_foreign_key('user_credentials_account_id_fkey', 'user_credentials', 'accounts', ['account_id'], ['id'])



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_credentials', 'account_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('historical_pnl', 'account_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('accounts', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
