"""Updated models

Revision ID: 33ca70e365ef
Revises: 098ab0564555
Create Date: 2024-10-16 10:19:47.795750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33ca70e365ef'
down_revision: Union[str, None] = '098ab0564555'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'type',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment="values: 'main' or 'secondary' where peopole will only visualize the trading data when desired",
               existing_nullable=True)
    op.add_column('user_configuration', sa.Column('oauth_synced', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_configuration', 'oauth_synced')
    op.alter_column('accounts', 'type',
               existing_type=sa.VARCHAR(length=255),
               comment="values: 'main' or 'secondary' where peopole will only visualize the trading data when desired",
               existing_nullable=True)
    # ### end Alembic commands ###
