"""Updated models

Revision ID: 43991c109c8b
Revises: d704cc786a42
Create Date: 2024-10-10 10:03:14.927958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43991c109c8b'
down_revision: Union[str, None] = 'd704cc786a42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('starred_cryptos', sa.Column('symbol', sa.Text(), nullable=True))
    op.drop_column('starred_cryptos', 'searchet_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('starred_cryptos', sa.Column('searchet_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('starred_cryptos', 'symbol')
    # ### end Alembic commands ###
