"""Updated models

Revision ID: 6a474fec0087
Revises: 8e8e2405d362
Create Date: 2024-10-07 15:25:55.956653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a474fec0087'
down_revision: Union[str, None] = '8e8e2405d362'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historical_searched_cryptos', sa.Column('name', sa.Text(), nullable=True))
    op.add_column('historical_searched_cryptos', sa.Column('picture_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('historical_searched_cryptos', 'picture_url')
    op.drop_column('historical_searched_cryptos', 'name')
    # ### end Alembic commands ###
