"""Updated models

Revision ID: 91d2f98a56eb
Revises: 036047780cb7
Create Date: 2024-09-25 10:01:24.188031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91d2f98a56eb'
down_revision: Union[str, None] = '036047780cb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('google_oauth', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('google_oauth_id_seq'::regclass)"))
    op.add_column('users', sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment="Posible values: 'user' normal user, 'moderator' moderator user with some admin permisions, 'administrator' admin users with all privilleges",
               existing_nullable=True,
               existing_server_default=sa.text('USER'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               comment="Posible values: 'user' normal user, 'moderator' moderator user with some admin permisions, 'administrator' admin users with all privilleges",
               existing_nullable=True,
               existing_server_default=sa.text('USER'))
    op.drop_column('users', 'joined_at')
    op.alter_column('google_oauth', 'id',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('google_oauth_id_seq'::regclass)"))
    # ### end Alembic commands ###
