"""Updated models

Revision ID: 9fd55c453b85
Revises: c5ddcd9b6e7f
Create Date: 2024-11-15 09:21:51.584457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fd55c453b85'
down_revision: Union[str, None] = 'c5ddcd9b6e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'proxy_ip',
               existing_type=sa.VARCHAR(length=355),
               type_=sa.String(length=255),
               comment=None,
               existing_comment='Asociated ip to this account',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'proxy_ip',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=355),
               comment='Asociated ip to this account',
               existing_nullable=True)
    # ### end Alembic commands ###
