"""Updated models

Revision ID: df8b3ef7ebfa
Revises: 80f3f00548d4
Create Date: 2024-10-18 16:57:18.062618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df8b3ef7ebfa'
down_revision: Union[str, None] = '80f3f00548d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_configuration', sa.Column('public_email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_configuration', 'public_email')
    # ### end Alembic commands ###
